### ISSUE TITLE
variable setting a bit broken

### ISSUE THREAD

**Issue by MinePossu** [adazem009/SMC#11]
setting a variable to "a b" only sets the variable a to a not to ab like set/"a","a b" and then print/a outputs a

**Comment by adazem009** [comment]
Can you describe the bug more please?

**Comment by MinePossu** [comment]
when setting a variable to a string the string will not include anything else after a space.

**Comment by adazem009** [comment]
This bug is probably caused by missing quotes in a process_argument function. A fix is coming soon.
