### ISSUE TITLE
Jump 1/!# broken must use 1/#

### ISSUE THREAD

**Issue by MinePossu** [adazem009/SMC#8]

**Comment by MinePossu** [comment]
i looked at jump command and command[1] which is process_argumented and agument[0] is 0. which is most likely wrong. so temp1 != "!" and then it uses else and it gets argument[0] which is 0 so its jumping to itself and being stuck there. cmds/1.sh script.

**Comment by adazem009** [comment]
This seems like a mistake in the documentation. Use `1/"!num"` because it's a string.
